module.exports = [
  { countryId: 1, name: 'Buenos Aires', code: 'BA' },
  { countryId: 1, name: 'Catamarca', code: 'CA' },
  { countryId: 1, name: 'Chaco', code: 'CH' },
  { countryId: 1, name: 'Chubut', code: 'CT' },
  { countryId: 1, name: 'Córdoba', code: 'CB' },
  { countryId: 1, name: 'Corrientes', code: 'CR' },
  { countryId: 1, name: 'Entre Ríos', code: 'ER' },
  { countryId: 1, name: 'Formosa', code: 'FO' },
  { countryId: 1, name: 'Jujuy', code: 'JY' },
  { countryId: 1, name: 'La Pampa', code: 'LP' },
  { countryId: 1, name: 'La Rioja', code: 'LR' },
  { countryId: 1, name: 'Mendoza', code: 'MZ' },
  { countryId: 1, name: 'Misiones', code: 'MI' },
  { countryId: 1, name: 'Neuquén', code: 'NQN' },
  { countryId: 1, name: 'Río Negro', code: 'RN' },
  { countryId: 1, name: 'Salta', code: 'SA' },
  { countryId: 1, name: 'San Juan', code: 'SJ' },
  { countryId: 1, name: 'San Luis', code: 'SL' },
  { countryId: 1, name: 'Santa Cruz', code: 'SC' },
  { countryId: 1, name: 'Santa Fe', code: 'SF' },
  { countryId: 1, name: 'Santiago del Estero', code: 'SE' },
  { countryId: 1, name: 'Tierra del Fuego', code: 'TF' },
  { countryId: 1, name: 'Tucumán', code: 'TU' },
];
